services:
  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/metadata
      - CHROMA_URL=http://chroma:8000
      - CLICKHOUSE_URL=http://clickhouse:8123
      # LLM API Keys (set these in your environment or .env file)
      # - GEMINI_API_KEY=your_gemini_api_key_here
      # - OPENAI_API_KEY=sk_your_openai_key_here
      # - YANDEX_API_KEY=your_yandex_api_key_here
      # - YANDEX_FOLDER_ID=your_yandex_folder_id_here
      # - GROQ_API_KEY=your_groq_api_key_here
      # - TOGETHER_API_KEY=your_together_key_here
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - chroma
      - clickhouse
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metadata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.4
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma:/chroma/.chroma
    ports:
      - "8001:8000"
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - chdata:/var/lib/clickhouse
volumes:
  pgdata: {}
  chroma: {}
  chdata: {}